# Generated by Django 6.0.6 on 2026-07-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('voter_hash', models.CharField(db_index=True, max_length=64)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='characters.character')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='rankings.characterranking')),
            ],
            options={
                'ordering': ['-voted_at'],
                'indexes': [models.Index(fields=['character', 'ip_hash', 'voted_at'], name='rankings_vo_charact_fd2005_idx'), models.Index(fields=['character', 'voter_hash', 'voted_at'], name='rankings_vo_charact_bc2c4a_idx')],
            },
        ),
    ]
