# Generated by Django 6.0.6 on 2026-07-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('rankings', '0009_characterranking_pfp_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterranking',
            name='votes',
            field=models.PositiveIntegerField(default=0, help_text='Current weekly vote count (resets each voting period).'),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Duelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(choices=[('eu', 'EU'), ('us', 'US'), ('au', 'AU')], max_length=2)),
                ('votes', models.PositiveIntegerField(default=0, help_text='Current weekly vote count (resets each voting period).')),
                ('all_time_votes', models.PositiveIntegerField(default=0, help_text='Total votes received across all weekly periods.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(help_text='The single Hero or Villain this duelist represents.', on_delete=django.db.models.deletion.PROTECT, related_name='duelists', to='characters.character')),
            ],
            options={
                'ordering': ['-votes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuelistVoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('voter_hash', models.CharField(db_index=True, max_length=64)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('duelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='rankings.duelist')),
            ],
            options={
                'ordering': ['-voted_at'],
                'indexes': [models.Index(fields=['ip_hash', 'voted_at'], name='rankings_du_ip_hash_f3e4e7_idx'), models.Index(fields=['voter_hash', 'voted_at'], name='rankings_du_voter_h_c27b99_idx')],
            },
        ),
    ]
