# Generated by Django 6.0.6 on 2026-07-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_combat_type'),
        ('rankings', '0014_align_weekly_period_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_burning',
            field=models.BooleanField(default=False, help_text='Show the burning nickname animation on this player everywhere.'),
        ),
        migrations.AlterField(
            model_name='duelist',
            name='character',
            field=models.ForeignKey(help_text='The single Saber Hero this duelist represents.', limit_choices_to={'combat_type': 'saber'}, on_delete=django.db.models.deletion.PROTECT, related_name='duelists', to='characters.character'),
        ),
    ]
