# Generated by Django 6.0.6 on 2026-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0015_player_name_burning'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_smoke',
            field=models.BooleanField(default=False, help_text='Show the smoke nickname animation on this player everywhere.'),
        ),
    ]
