# Generated by Django 6.0.6 on 2026-07-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0016_player_name_smoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_glitch',
            field=models.BooleanField(default=False, help_text='Show the glitch nickname animation on this player everywhere.'),
        ),
    ]
