# Generated by Django 6.0.6 on 2026-07-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0017_player_name_glitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_url',
            field=models.URLField(blank=True, help_text='Public Discord profile or invite link for this player.'),
        ),
        migrations.AddField(
            model_name='player',
            name='steam_url',
            field=models.URLField(blank=True, help_text='Public Steam profile link for this player.'),
        ),
    ]
