# Generated by Django 6.0.6 on 2026-07-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0018_player_discord_steam_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitch_url',
            field=models.URLField(blank=True, help_text='Public Twitch channel link for this player.'),
        ),
    ]
