# Generated by Django 6.0.7 on 2026-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0019_player_twitch_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('pfp_weekly_ending', 'PFP weekly ending rankings'), ('eu_duelist_weekly_winners', 'EU duelist weekly winners'), ('us_duelist_weekly_winners', 'US duelist weekly winners'), ('au_duelist_weekly_winners', 'AU duelist weekly winners')], max_length=64),
        ),
    ]
